#################################################################
###                                                           ###
###                    InfamousCORE Config                    ###
###                           v2.0.0                          ###
###                                                           ###
#################################################################

# MySQL Login
# MySQL is required for the following modules:
# - Homes
# If a connection is not found, these modules will be disabled
mysql:
  host:
  port:
  database:
  username:
  password:

###
# HOME MODULE
###
home:
  restricted-worlds:
    - world_name_1
    - world_name_2
  max-permission-check: 50 # The max amount of homes a player can have via "core.sethome.max.<#>"

###
# COOLDOWNS
###
cooldown: # The amount of time (in seconds) a player must wait before...
  home: 5 # ...teleporting to a home
  spawn: 0 # ...teleporting to spawn
  heal: 60 # ...using /heal
  feed: 60 # ...using /feed

###
# WARMUPS
###
warmup:
  teleport: 3